=== BattMoTeam/BattMo/Utilities/JsonSchemas/battery.schema.json
{
  "$id": "file://batmo/schemas/battery",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A standard battery",
  "type": "object",
  "properties" : {
    "SOC" : {"type" : "number"},
    "Ucut" : {"type" : "number",
              "description" : "cut voltage"},
    "initT" : {"type" : "number",
               "description" : "Initial temperature"},
    "NegativeElectrode" : {"$ref": "electrode"},
    "PositiveElectrode" : {"$ref": "electrode"},
    "Electrolyte" : {"$ref": "binaryelectrolyte"},
    "ThermalModel" : {"$ref": "thermalmodel"}
  }
}

=== BattMoTeam/BattMo/ParameterData/ParameterSets/Chen2020/chen2020_lithium_ion_battery.json
{
    "initT": 298.15,
    "NegativeElectrode": {
        "electricalConductivity": 215,
        "heatCapacity": 4180000.0,
        "thermalConductivity": 6e-05,
        "InterDiffusionCoefficient": 1e-10,
        "Interface": {
            "isFile": true,
            "filename": "ParameterData/ParameterSets/Chen2020/chen2020_negative_electrode_interface.json"
        },
        "SolidDiffusion" : {
            "useSimplifiedDiffusionModel" : true,
            "EaD": 0,
            "D0": 3.3e-14,
            "rp": 5.86e-06
        }

    },
    "PositiveElectrode": {
        "electricalConductivity": 0.18,
        "heatCapacity": 4180000.0,
        "thermalConductivity": 6e-05,
        "InterDiffusionCoefficient": 1e-10,
        "Interface": {
            "isFile": true,
            "filename": "ParameterData/ParameterSets/Chen2020/chen2020_positive_electrode_interface.json"
        },
        "SolidDiffusion": {
            "useSimplifiedDiffusionModel" : true,
            "EaD": 0,
            "D0": 4e-15,
            "rp": 5.22e-6
        }
    },
    "Electrolyte": {
        "filename": "ParameterData/ParameterSets/Chen2020/chen2020_electrolyte.json",
        "isFile": true
    }
}

=== BattMoTeam/BattMo/JsonDatas/Chen2020/chenBattery.json
{
    "initT": 298.15,
    "NegativeElectrode": {
        "electricalConductivity": 215,
        "heatCapacity": 4180000.0,
        "thermalConductivity": 6e-05,
        "InterDiffusionCoefficient": 1e-10,
        "chargeCarrierName": "Li",
        "Interface": {
            "isFile": true,
            "filename": "JsonDatas/Chen2020/chenNegativeElectrodeInterface.json"
        }
    },
    "PositiveElectrode": {
        "electricalConductivity": 0.18,
        "heatCapacity": 4180000.0,
        "thermalConductivity": 6e-05,
        "InterDiffusionCoefficient": 1e-10,
        "chargeCarrierName": "Li",
        "Interface": {
            "isFile": true,
            "filename": "JsonDatas/Chen2020/chenPositiveElectrodeInterface.json"
        }
    },
    "Electrolyte": {
        "filename": "JsonDatas/Chen2020/chenElectrolyte.json",
        "isFile": true
    }
}
