=== BattMoTeam/BattMo/Electrolyser/JsonSchemas/Electrolyser.schema.json
{
  "$id": "file://battmo/schemas/Electrolyser",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A standard electrolyser",
  "type": "object",
  
  "properties" : {

    "referencePotential" : {
      "$ref": "PhysicalQuantity.schema.json",
      "description" : "Reference potential",
      "symbol" : "Eref"},
    
    "IonomerMembrane": {
      "$ref": "IonomerMembrane"},

    "HydrogenEvolutionElectrode": {
      "$ref": "EvolutionElectrode"},
    
    "OxygenEvolutionElectrode": {
      "$ref": "EvolutionElectrode"}}}

=== BattMoTeam/BattMo/Electrolyser/Parameters/alkalineElectrolyser.json
{
  "referencePotential" : -0.8227,
  "IonomerMembrane": {
    "liquidVolumeFraction" : 0.9,
    "H2O" : {"referenceConcentration" : 1000,
             "diffusionCoefficient" : 1.0751e-9,
             "partialMolarVolume": 18e-6},
    "OH" : {"occupationNumber" : 1,
            "chargeNumber" : -1,
            "transference" : 1},
    "molarVolume" : 7.6e-4,
    "totalChargedGroupConcentration" : 1315,
    "conductivity" : 13
  },
  "HydrogenEvolutionElectrode": {
    "porousTransportLayerType" : "Hydrogen",
    "PorousTransportLayer" : {
      "solidVolumefraction": 0.33,
      "leverettCoefficients": [ -1.11178e-1,
                                1.39e-3,
                                1.422e-2,
                                12.80,
                                -7.614],
      "waterContactAngle": 100,
      "permeability": 1e-12,
      "tortuosity": 1.5,
      "species": {
        "OH": {
          "molecularWeight": 0.0170068,
          "partialMolarVolume": -3.98e-6,
          "diffusionCoefficient": 3.5e-9,
          "transference": 0.728,
          "chargeNumber": -1
        },
        "K": {
          "molecularWeight": 0.0390983,
          "partialMolarVolume": 9.02e-6,
          "transference" : 0.27
        },
        "H2O": {
          "molecularWeight": 0.0180147,
          "partialMolarVolume": 18e-6,
          "liquidVaporExchangeRate": 1000,
          "standardChemicalPotential": -237140
        },
        "H2" : {
          "molecularWeight" : 0.00202
        }
      },
      "molecularWeight" : 0.0561056
    },
    "catalystLayerType" : "Platinium",
    "CatalystLayer" : { "referenceExchangeCurrentDensity": 8.885,
                        "standardEquilibriumPotential" : -0.8227,
                        "species" : {"OH" : {"chargeNumber" : -1,
                                             "referenceConcentration" : 1000}},
                        "numberOfElectronsTransferred" : 1,
                        "chargeTransferCoefficient" : 0.5,
                        "ionomerFractionArea" : 0.5,
                        "referenceVolumetricSurfaceArea" : 2e6,
                        "tortuosity" : 1.5
                      },
    "ExchangeReaction" : {
      "OH" : {"chargeNumber" : -1,
              "referenceConcentration" : 1000},
      "exchangeReactionRate" : 100000,
      "ionomerSorptionCoefficient" : 5e6
    }
  },
  
  "OxygenEvolutionElectrode": {
    "porousTransportLayerType" : "Oxygen",
    "PorousTransportLayer" : {
      "solidVolumefraction": 0.33,
      "leverettCoefficients": [ -1.11178e-1,
                                1.39e-3,
                                1.422e-2,
                                12.80,
                                -7.614],
      "waterContactAngle": 100,
      "permeability": 1e-12,
      "tortuosity": 1.5,
      "species": {
        "OH": {
          "molecularWeight": 0.0170068,
          "partialMolarVolume": -3.98e-6,
          "diffusionCoefficient": 3.5e-9,
          "transference": 0.728,
          "chargeNumber": -1
        },
        "K": {
          "molecularWeight": 0.0390983,
          "partialMolarVolume": 9.02e-6,
          "transference" : 0.27
        },
        "H2O": {
          "molecularWeight": 0.0180147,
          "partialMolarVolume": 18e-6,
          "liquidVaporExchangeRate": 1000,
          "standardChemicalPotential": -237140
        },
        "O2" : {
          "molecularWeight" : 0.031998
        }
      },
      "molecularWeight" : 0.0561056
    },
    "catalystLayerType" : "Iridium",
    "CatalystLayer" : { "referenceExchangeCurrentDensity": 0.256,
                        "standardEquilibriumPotential" : 0.401,
                        "species" : {"OH" : {"chargeNumber" : -1,
                                             "referenceConcentration" : 1000}},
                        "numberOfElectronsTransferred" : 1,
                        "chargeTransferCoefficient" : 0.5,
                        "ionomerFractionArea" : 0.5,
                        "referenceVolumetricSurfaceArea" : 2e6,
                        "tortuosity" : 1.5
                      },
    "ExchangeReaction" : {
      "OH" : {"chargeNumber" : -1,
              "referenceConcentration" : 1000},
      "exchangeReactionRate" : 100000,
      "ionomerSorptionCoefficient" : 5e6
    }
  }
  
}
